apiVersion: v1
kind: Pod
metadata: 
  name: nginx
  namespace: roboshop-dev
  labels:
    project: roboshop
    environment: development
spec:    
  containers:
  - name: nginx
    image: nginx:1.24
    ports:
    - containerPort: 80


















      
