apiVersion: v1
kind: Pod
metadata:
  name: multi-container
  labels:
    purpose: multi-container
spec:
  containers:
  - name: nginx
    image: nginx:1.24
    ports:
    - containerPort: 80
  - name: almalinux
    image: almalinux:9
    command: ["sleep", "1000"]
