apiVersion: v1
kind: Pod
metadata:
  name: labels
  labels: 
    project: roboshop
    environment: dev
    component: frontend
    version: v1
spec:
  containers:
  - name: frontend
    image: nginx:1.24
    ports:
    - containerPort: 80

