apiVersion: v1
kind: Pod
metadata:
  name: annotations
  annotations: 
    jenkins_url: "http://jenkins.sniggie.fun"
    imageregistry: "https://hub.docker.com/"
spec:
  containers:
  - name: nginx
    image: nginx:1.24


