apiVersion: v1
kind: Pod
metadata:
  name: resources
  labels:
    purpose: resources-demo
spec:
  containers:
    - name: nginx
      image: nginx:1.24
      resources:
      requests:
        memory: "64Mi"
        cpu: "100m"
      limits:
        memory: "100Mi"
        cpu: "150m"
