apiVersion: v1
kind: Pod
metadata:
  name: service-cp
  # These labels are used to register this pod with service
  labels: 
    project: roboshop
    component: frontend
    environment: dev
spec:
  containers:
    - name: nginx-cp
      image: nginx:1.24
      ports:
        - containerPort: 80