apiVersion: v1
kind: Pod
metadata:
  name: service-lb
  # These labels are used to register this pod with service
  labels: 
    project: roboshop
    component: frontend
    environment: dev
    purpose: load-balancer
spec:
  containers:
    - name: nginx-lb
      image: nginx:1.24
      ports:
        - containerPort: 80